name: Create Build Pipeline

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test --if-present

      - name: Run Code Coverage
        run: npm run test:coverage --if-present

      - name: Get Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bulletin-board-app:bb-${{ steps.vars.outputs.sha_short }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/bulletin-board-app:bb-${{ steps.vars.outputs.sha_short }}  
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test --if-present

      - name: Run Code Coverage
        run: npm run test:coverage --if-present

      - name: Get Short SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bulletin-board-app:bb-${{ steps.vars.outputs.sha_short }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/bulletin-board-app:bb-${{ steps.vars.outputs.sha_short }}